/** Gardiens sur leurs grilles natives 44×44, 32×32 et 40×40. Un caractère = un pixel, lumière en haut à gauche.
 * Palette partagée avec les ennemis : pierre, bordeaux, ivoire et bronze terni.
 * Les masses et les silhouettes sont conçues sur cette grille, sans redimensionnement. */
import type { SpriteMonstre } from '@/content/types';

export const PALETTE_GARDIENS: Record<string,string> = {
  'X': '#25232d',
  'd': '#393744',
  'g': '#555463',
  'l': '#787986',
  'k': '#685739',
  'b': '#a4864d',
  'h': '#ceaa62',
  'w': '#e9ddbc',
  'i': '#f3d2aa',
  'p': '#c28b71',
  'f': '#e4b593',
  'q': '#936954',
  'r': '#922e3b',
  's': '#62303b',
  't': '#513b30',
  'o': '#76523a',
  'u': '#a0784d',
  'v': '#c29865',
  'e': '#697e7e',
  'a': '#9eb5ac',
  'c': '#d4e0cb',
};
export type SpriteGardien = Extract<SpriteMonstre,'prevot'|'pressoir'|'spectre'>;
export const PIXELS_GARDIENS: Record<SpriteGardien,readonly string[]> = {
  prevot: [
    '............................................',
    '............................................',
    '............................................',
    '.................kkkkkkkkkk.................',
    '.................wiiiiiwwwk.................',
    '..............kkkwwwwwwwwwkkkk..............',
    '..............kiiiiiihhwwwwwwk..............',
    '.....kwwk.....ksssssshhssssssk..............',
    '.....kiwk....kkkkkkkkkkkkkkkkkk.............',
    '....kiiwwk...kkkkkkkkkkkkkkkkkk.............',
    '....kiiwwk.......piiiffffpp.................',
    '....kiiwwk.......pdddffdddq.................',
    '....kwwwwk.......pfXfiifXqq.................',
    '....kwwwwk.......pfffiiffqq.................',
    '....kkkkkk.......pfffiiqfqq.................',
    '.....hhhh........pfppppppqq.................',
    '.....kkkk........pppqqqqppp.................',
    '......bt............pppp....................',
    '......bt..khhhbkk.wwwwwwwww..bhhbk..........',
    '......bt..kbbbbkksiiwwwwwwwssbbbbk..........',
    '......bt..kkkkkkkriiwwwwwiwrrkkkkks.........',
    '......bt.sssrrrrrwiiwwwwwiwrrrsrrss.........',
    '......bt.srrrrrrrwihrrrrhiwrrrsrrbbbbbbb....',
    '......bt.srrsrrrrwiihrrhwiwrrrsrrkiwwwwk....',
    '......bt.srrsrrrrwiirhhrwiwrrrsrrkiwwwwk....',
    '......bt.srrsrrrrwiirhhrwiwrrrsrrkiwwwwk....',
    '......bt.srrssrrrwiirhhrwiwssrsrrkigggwk....',
    '......bt.srrrrrsswiirrrrwiwssrsrrkiwwwwk....',
    '......bt.srrrrrsswiirrrrwwwssrsrrkigggwk....',
    '......bt.srrrrrsswwwrrrrwwwssssrrkiwwwwk....',
    '......bt.srrsrrsswwwrrrrwwwsssspfkiwrrwk....',
    '......bfffppsrrsshhhrrrrhhhssssppkiwrrwk....',
    '......bfffppsrrsshhhrrrrhhhssssppkiwrrwk....',
    '......bfffpprrrsskkkrrsrkkkssssppkwwwwwk....',
    '......btpppprrrsskkkrrsskkkssrrr.bbbbbbb....',
    '......bt...srrrssssssssssssrrrrrsbbbbbbb....',
    '......bt...srrrrrrsssssssssrrrrrs...........',
    '......bt...sssssssXX.....Xsssssss...........',
    '......tt.....ggXXXXX.....XgXXXXX............',
    '.............XXXXXXX.....XXXXXXX............',
    '...........XXXXXXXXX.....XXXXXXXXX..........',
    '...........XXXXXXXXX.....XXXXXXXXX..........',
    '............................................',
    '............................................',
  ],
  pressoir: [
    '................................',
    '.........lllllllllllld..........',
    '.......lldddddgggdddddll........',
    '.......ddd...dgggd...ddd........',
    '.............dgggd..............',
    '.............dllll..............',
    '..tuvvvvvuuuudgggduuuuuuuuuttt..',
    '..tobbooooooodgggdoooooobboott..',
    '..toooooooooollllloooooooooott..',
    '..tdlllldttttdgggdtttttdllllld..',
    '...ddhddd....ddddd.....ddddhdd..',
    '....tvotkkkkkkkkkkkkkkk.tuoot...',
    '....tvotkkkkkkkkkkkkkkk.tuoot...',
    '....tvot.tvuoovoouuoot..tutot...',
    '....tvot.tttttvoottttt..tutot...',
    '....tuot.tvhhhvoohhhot..tuoot...',
    '....tutt.tvuoouoouuoot..tuoot...',
    '....tutt.tuuoouoouuoot..tuoot...',
    '....tuotddddddddddddddd.tuoot...',
    '....tuollllllllllllllllgduoot...',
    '....tuogggggggggggggggggduoot...',
    '....tuoggwwXXwwXXwwXXwggduoot...',
    '....tuoggXXXXwwXXwwXXXggduoot...',
    '....tuoggXXXXXXwwXXXXXggduoot...',
    '...dlllggXXwwXXwwXXXwwggdlllld..',
    '...ddhdggggggsssssggggggdddhdd..',
    '...ddddddddddddddddddddddddddd..',
    '....tttllllllllllllllllldtttt...',
    '..tvvvvvvvuuuuuuuutttuuuuuuott..',
    '..tooooooooooooooooooooooooott..',
    '..tttttttttttttttttttttttttttt..',
    '.....tttt..............ttttt....',
  ],
  spectre: [
    '........................................',
    '........................................',
    '..................eee...................',
    '..................aae...................',
    '................eeaaeee.................',
    '................acccaae.................',
    '................acccaae.................',
    '..............eeaaaaaaeee...............',
    '..............acccaaaaaae...............',
    '..............acccaaaaaae...............',
    '............eeaeeeeeeeeeeee.............',
    '............eccdcceeeccdaee.............',
    '............eccdddecedddaee.............',
    '............ecceeeeceeeeaee.............',
    '............ecceeeeceeeeaee.............',
    '............ecceeeaaaeeeaee.............',
    '............eeeeeeeeeeeeeee.............',
    '..........eekhhkeeeeeeekhbkee...........',
    '.....eccaaeakbbkaaaaaaakbbkeeeaaaee.....',
    '.....eccaaeakkkbhhhbbbbkkkkeeeaaaee.....',
    '.....eaaaaeccaakkkkkkkkkaaaeeeaaaee.....',
    '.....eeeebeccaeeaaccaaeeaaaeebeeeee.....',
    '...ecaae.keccaeeaaccaaeeaaaeek...eaae...',
    '...ecaae..kccaeeaaccaaeeaaaek....eaae...',
    '...eeece..bccaeeaaccaaeeaaaeb....eeec...',
    '...ececeeaaccaaaaaccaaeeaaaaeeee.ecec...',
    '....c...eaakhhhhhbbbbbbbbbbkkeee..c.....',
    '....c...ecckkkkkkkhhhkkkkkkkkeee..c.....',
    '........ecckkkkkkkhhhkkkkkkkkeee........',
    '........eccaaaeeaaccaaaaeeaaeeee........',
    '........eccaaaeeaaccaaaaeeeeeeee........',
    '........eccaaeeeaaccaaaaeeeeeeee........',
    '.......ccccaaeaeaacaaaaaeeaeaaeee.......',
    '......eaaaaaaeaeaacaaaaaeeaaaaeeee......',
    '......eeaaae.eaeeacaae.eeeaeaaeeee......',
    '........aaae....eaaaaee....eee..........',
    '.......eeeeee....aaaaee....eee..........',
    '.................eeeeee.................',
    '........................................',
    '........................................',
  ],
};
export const DESSINS_GARDIENS = Object.fromEntries(
  (Object.keys(PIXELS_GARDIENS) as SpriteGardien[]).map(id=>[id,(g:CanvasRenderingContext2D)=>{
    PIXELS_GARDIENS[id].forEach((ligne,y)=>[...ligne].forEach((pixel,x)=>{
      if(pixel!=='.'){g.fillStyle=PALETTE_GARDIENS[pixel]!;g.fillRect(x,y,1,1);}
    }));
  }]),
) as Record<SpriteGardien,(g:CanvasRenderingContext2D)=>void>;
