/** Gardiens natifs 40×40. Un caractère = un pixel, lumière en haut à gauche.
 * Palette partagée avec les ennemis : pierre, bordeaux, ivoire et bronze terni.
 * Les masses et les silhouettes sont conçues sur cette grille, sans redimensionnement. */
import type { SpriteMonstre } from '@/content/types';

export const PALETTE_GARDIENS: Record<string,string> = {
  'X': '#25232d',
  'd': '#393744',
  'g': '#555463',
  'l': '#787986',
  'k': '#685739',
  'b': '#a4864d',
  'h': '#ceaa62',
  'w': '#e9ddbc',
  'i': '#f3d2aa',
  'p': '#c28b71',
  'f': '#e4b593',
  'q': '#936954',
  'r': '#922e3b',
  's': '#62303b',
  't': '#513b30',
  'o': '#76523a',
  'u': '#a0784d',
  'v': '#c29865',
  'e': '#697e7e',
  'a': '#9eb5ac',
  'c': '#d4e0cb',
};
export type SpriteGardien = Extract<SpriteMonstre,'prevot'|'pressoir'|'spectre'>;
export const PIXELS_GARDIENS: Record<SpriteGardien,readonly string[]> = {
  prevot: [
    '........................................',
    '........................................',
    '...............kkkkkkkkkk...............',
    '...............wiiiiiwwwk...............',
    '.............kkwwwwwwwwwkkk.............',
    '.............kiiiiihhwwwwwk.............',
    '....kwwk.....kssssshhsssssk.............',
    '....kiwk....kkkkkkkkkkkkkkkk............',
    '...kiiwwk...kkkkkkkkkkkkkkkk............',
    '...kiiwwk......piiiffffpp...............',
    '...kiiwwk......pdddffdddq...............',
    '...kwwwwk......pfXfiifXqq...............',
    '...kwwwwk......pfffiiffqq...............',
    '...kkkkkk......pfffiiqfqq...............',
    '....hhhh.......pfppppppqq...............',
    '....kkkk.......pppqqqqppp...............',
    '.....bt...........pppp..................',
    '.....bt..khhhbk.wwwwwwwww.bhhbk.........',
    '.....bt..kbbbbksiiwwwwwwwsbbbbk.........',
    '.....bt..kkkkkkriiwwwwwiwrkkkkks........',
    '.....bt.sssrrrrwiiwwwwwiwrrsrrss........',
    '.....bt.srrrrrrwihrrrrhiwrrsrrbbbbbbb...',
    '.....bt.srrsrrrwiihrrhwiwrrsrrkiwwwwk...',
    '.....bt.srrsrrrwiirhhrwiwrrsrrkiwwwwk...',
    '.....bt.srrssrrwiirhhrwiwsrsrrkigggwk...',
    '.....bt.srrrrrswiirrrrwiwsrsrrkiwwwwk...',
    '.....bt.srrrrrswiirrrrwwwsrsrrkigggwk...',
    '.....bt.srrrrrswwwrrrrwwwsssrrkiwwwwk...',
    '.....bt.srrsrrswwwrrrrwwwssspfkiwrrwk...',
    '.....bfffppsrrshhhrrrrhhhsssppkiwrrwk...',
    '.....bfffpprrrskkkrrsrkkksssppkwwwwwk...',
    '.....btpppprrrskkkrrsskkksrrr.bbbbbbb...',
    '.....bt...srrrsssssssssssrrrrsbbbbbbb...',
    '.....bt...srrrrrsssssssssrrrrs..........',
    '.....bt...ssssssXX.....Xssssss..........',
    '.....tt.....ggXXXX.....XgXXXX...........',
    '............XXXXXX.....XXXXXX...........',
    '..........XXXXXXXX.....XXXXXXXX.........',
    '..........XXXXXXXX.....XXXXXXXX.........',
    '........................................',
  ],
  pressoir: [
    '........................................',
    '........................................',
    '........................................',
    '.............llllllllllllld.............',
    '...........lldddddggggdddddll...........',
    '...........ddd...dggggd...ddd...........',
    '.................llllll.................',
    '.................dggggd.................',
    '.................dggggd.................',
    '.................dlllll.................',
    '.....tuvvvvvvuuuudggggduuuuuuuuuttt.....',
    '.....tobboooooooodggggdoooooobboott.....',
    '.....tooooooooooolllllloooooooooott.....',
    '.....tdllllldttttdggggdtttttdllllld.....',
    '......ddhdddd....dddddd.....ddddhdd.....',
    '......ddddddkbbbbbbbbbbbbbbkddddddd.....',
    '.......tvootkkkkkkkkkkkkkkkk.tuoot......',
    '.......tvootkkkkkkkkkkkkkkkk.tuoot......',
    '.......tvoot.tvuoovuoouuoot..tutot......',
    '.......tvoot.tttttvuoottttt..tutot......',
    '.......tuoot.tvhhhvuoohhhot..tuoot......',
    '.......tuoot.tvhhXuuooXhhot..tuoot......',
    '.......tutot.tvuoouuoouuoot..tuoot......',
    '.......tuuot.tuuoouuoouuoot..tuoot......',
    '.......tutot.tuuoouuoouuoot..tuoot......',
    '.......tuootdddddddddddddddd.tuoot......',
    '.......tuodlllllllllllllllllgduoot......',
    '.......tuodggggggggggggggggggduoot......',
    '.......tuodggwwXXwwXXXwwXXwggduoot......',
    '.......tuodggXXXXwwXXXwwXXXggduoot......',
    '.......tuodggXXXXXXXwwXXXXXggduoot......',
    '......dllldggXXwwXXXwwXXXwwggdlllld.....',
    '......ddhddggggggssssssggggggdddhdd.....',
    '......ddddddddddddddddddddddddddddd.....',
    '.......tttdlllllllllllllllllldtttt......',
    '.....tvvvvvvvvuuuuuuuuutttuuuuuuott.....',
    '.....tooooooooooooooooooooooooooott.....',
    '.....tttttttttttttttttttttttttttttt.....',
    '........ttttt...............ttttt.......',
    '........................................',
  ],
  spectre: [
    '........................................',
    '........................................',
    '..................eee...................',
    '..................aae...................',
    '................eeaaeee.................',
    '................acccaae.................',
    '................acccaae.................',
    '..............eeaaaaaaeee...............',
    '..............acccaaaaaae...............',
    '..............acccaaaaaae...............',
    '............eeaeeeeeeeeeeee.............',
    '............eccdcceeeccdaee.............',
    '............eccdddecedddaee.............',
    '............ecceeeeceeeeaee.............',
    '............ecceeeeceeeeaee.............',
    '............ecceeeaaaeeeaee.............',
    '............eeeeeeeeeeeeeee.............',
    '..........eekhhkeeeeeeekhbkee...........',
    '.....eccaaeakbbkaaaaaaakbbkeeeaaaee.....',
    '.....eccaaeakkkbhhhbbbbkkkkeeeaaaee.....',
    '.....eaaaaeccaakkkkkkkkkaaaeeeaaaee.....',
    '.....eeeebeccaeeaaccaaeeaaaeebeeeee.....',
    '...ecaae.keccaeeaaccaaeeaaaeek...eaae...',
    '...ecaae..kccaeeaaccaaeeaaaek....eaae...',
    '...eeece..bccaeeaaccaaeeaaaeb....eeec...',
    '...ececeeaaccaaaaaccaaeeaaaaeeee.ecec...',
    '....c...eaakhhhhhbbbbbbbbbbkkeee..c.....',
    '....c...ecckkkkkkkhhhkkkkkkkkeee..c.....',
    '........ecckkkkkkkhhhkkkkkkkkeee........',
    '........eccaaaeeaaccaaaaeeaaeeee........',
    '........eccaaaeeaaccaaaaeeeeeeee........',
    '........eccaaeeeaaccaaaaeeeeeeee........',
    '.......ccccaaeaeaacaaaaaeeaeaaeee.......',
    '......eaaaaaaeaeaacaaaaaeeaaaaeeee......',
    '......eeaaae.eaeeacaae.eeeaeaaeeee......',
    '........aaae....eaaaaee....eee..........',
    '.......eeeeee....aaaaee....eee..........',
    '.................eeeeee.................',
    '........................................',
    '........................................',
  ],
};
export const TAILLES_GARDIENS: Record<SpriteGardien,number> = {prevot:.86,pressoir:.66,spectre:.8};
export const DESSINS_GARDIENS = Object.fromEntries(
  (Object.keys(PIXELS_GARDIENS) as SpriteGardien[]).map(id=>[id,(g:CanvasRenderingContext2D)=>{
    PIXELS_GARDIENS[id].forEach((ligne,y)=>[...ligne].forEach((pixel,x)=>{
      if(pixel!=='.'){g.fillStyle=PALETTE_GARDIENS[pixel]!;g.fillRect(x,y,1,1);}
    }));
    return TAILLES_GARDIENS[id];
  }]),
) as Record<SpriteGardien,(g:CanvasRenderingContext2D)=>number>;
