/** Objets au sol : dessins natifs adaptés à leur taille, distincts des icônes d'inventaire. */
import type { Objet3D } from './grille-pixels';
const PALETTE: Record<string, string> = {
  b:'#513b30', o:'#76523a', u:'#a0784d', s:'#39312b',
  w:'#e9ddbc', i:'#f3d2aa', r:'#922e3b', R:'#62303b', p:'#c28b71',
  v:'#73845a', e:'#4a593e', m:'#73845a', G:'#ceaa62', g:'#a4864d',
  l:'#a5b782', d:'#393744',
};
export const PIXELS_OBJETS_SOL: Record<Objet3D, readonly string[]> = {
  jambon: [
    '..............',
    '.........ww...',
    '........wiiw..',
    '........wio...',
    '........ob....',
    '.....bbbob....',
    '....brrbbb....',
    '...bppprrbo...',
    '..bppprrrrbo..',
    '..bprrsrrrbo..',
    '..brrrrssrbo..',
    '...brrrssbo...',
    '....bbbbb.....',
    '..............',
  ],
  biere: [
    '................',
    '.......GG.......',
    '.......go.......',
    '.......ve.......',
    '.......ve.......',
    '......vlee......',
    '.....vlmmee.....',
    '....vlmmmeee....',
    '....vlmmmeee....',
    '....bwwwbbbe....',
    '....bwoooobe....',
    '....bwwRRbbe....',
    '....bwwRRbbe....',
    '....vlmmmmme....',
    '....eeeeeeee....',
    '................',
  ],
  sac: [
    '................',
    '................',
    '.......bbb......',
    '......buub......',
    '......buub......',
    '......bbbb......',
    '.....buuoob.....',
    '....buoooosb....',
    '...buooooossb...',
    '..buoooGGossb...',
    '..buoooGgossb...',
    '..buoooooossb...',
    '...boooooosb....',
    '....bsssssb.....',
    '.....bbbbb......',
    '................',
  ],
  tonneau: [
    '....................',
    '....................',
    '.......bbbbbb.......',
    '.....buuuuuuusb.....',
    '....buoooooossb.....',
    '....buloouoossb.....',
    '...blllllllddddb....',
    '...blgggggggggdb....',
    '...buloouoouossb....',
    '...buloouoouossb....',
    '...buloouoouossb....',
    '...buloGGouuossb....',
    '...buloGgouuossb....',
    '...buloouoouossb....',
    '...blllllllddddb....',
    '...bggggggggggdb....',
    '....booooooossb.....',
    '.....bsssssssb......',
    '.......bbbbbb.......',
    '....................',
  ],
};
export function dessinerObjetSol(g: CanvasRenderingContext2D, type: Objet3D) {
  PIXELS_OBJETS_SOL[type].forEach((ligne,y)=>[...ligne].forEach((pixel,x)=>{
    const couleur=PALETTE[pixel];
    if(couleur){g.fillStyle=couleur;g.fillRect(x,y,1,1);}
  }));
}
